# Uncomment the next line to define a global platform for your project
#platform :ios, '13.0'

target 'SDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKDemo

  pod 'QuadPaySDK',  :path => '../'

  target 'SDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'QuadPaySDK'
      target.build_configurations.each do |config|
        if config.name == 'Debug'
          config.build_settings['SWIFT_ACTIVE_COMPILATION_CONDITIONS'] = 'QUADPAY_SDK_DEVELOPMENT'
        end
      end
    end
  end
end
