# Uncomment the next line to define a global platform for your project
#platform :ios, '13.0'

target 'SDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKDemo

  pod 'QuadPaySDK',  :path => '../', :configurations => ['Debug']

  target 'SDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKDemoUITests' do
    # Pods for testing
  end

end
