//
// Generated by CocoaPods-Keys
// on 05/10/2022
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface QuadPaySDKXcodeprojKeys : NSObject

@property (readonly) NSString *segmentWriteKey;

@end

NS_ASSUME_NONNULL_END
