# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKExample

  pod 'QuadPaySDK',  :path => '../../'

  target 'SDKExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKExampleUITests' do
    # Pods for testing
  end

end
