# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDKTestSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKTestSwift
  # For local SDK
  # pod 'QuadPaySDK',  :path => '../', :configurations => ['Debug']
  # For deployed SDK
  pod 'QuadPaySDK', '~> 0.3.9', :configurations => ['Debug']

  target 'SDKTestSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SDKTestSwiftUITests' do
    # Pods for testing
  end

end
