//
// Generated by CocoaPods-Keys
// on 05/10/2022
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSDictionary.h>
#import "QuadPaySDKXcodeprojKeys.h"

@interface QuadPaySDKXcodeprojKeys ()

@property (nonatomic, copy) NSString *segmentWriteKey;


@end

@implementation QuadPaySDKXcodeprojKeys

- (instancetype)init
{
    if (!(self = [super init])) { return nil; }

    
    
      char segmentWriteKeyCString[33] = { [QuadPaySDKXcodeprojKeysData characterAtIndex:65], [QuadPaySDKXcodeprojKeysData characterAtIndex:404], [QuadPaySDKXcodeprojKeysData characterAtIndex:913], [QuadPaySDKXcodeprojKeysData characterAtIndex:437], [QuadPaySDKXcodeprojKeysData characterAtIndex:114], [QuadPaySDKXcodeprojKeysData characterAtIndex:870], [QuadPaySDKXcodeprojKeysData characterAtIndex:1016], [QuadPaySDKXcodeprojKeysData characterAtIndex:343], [QuadPaySDKXcodeprojKeysData characterAtIndex:159], [QuadPaySDKXcodeprojKeysData characterAtIndex:472], [QuadPaySDKXcodeprojKeysData characterAtIndex:5], [QuadPaySDKXcodeprojKeysData characterAtIndex:954], [QuadPaySDKXcodeprojKeysData characterAtIndex:936], [QuadPaySDKXcodeprojKeysData characterAtIndex:19], [QuadPaySDKXcodeprojKeysData characterAtIndex:506], [QuadPaySDKXcodeprojKeysData characterAtIndex:364], [QuadPaySDKXcodeprojKeysData characterAtIndex:339], [QuadPaySDKXcodeprojKeysData characterAtIndex:899], [QuadPaySDKXcodeprojKeysData characterAtIndex:106], [QuadPaySDKXcodeprojKeysData characterAtIndex:858], [QuadPaySDKXcodeprojKeysData characterAtIndex:406], [QuadPaySDKXcodeprojKeysData characterAtIndex:669], [QuadPaySDKXcodeprojKeysData characterAtIndex:964], [QuadPaySDKXcodeprojKeysData characterAtIndex:37], [QuadPaySDKXcodeprojKeysData characterAtIndex:811], [QuadPaySDKXcodeprojKeysData characterAtIndex:418], [QuadPaySDKXcodeprojKeysData characterAtIndex:715], [QuadPaySDKXcodeprojKeysData characterAtIndex:901], [QuadPaySDKXcodeprojKeysData characterAtIndex:142], [QuadPaySDKXcodeprojKeysData characterAtIndex:257], [QuadPaySDKXcodeprojKeysData characterAtIndex:640], [QuadPaySDKXcodeprojKeysData characterAtIndex:931], '\0' };
    
    _segmentWriteKey = 
        
          [NSString stringWithCString:segmentWriteKeyCString encoding:NSUTF8StringEncoding];
        
      
    

    return self;
}

static NSString *QuadPaySDKXcodeprojKeysData = @"QjqTfASnVfIq82C3M8fipf/esvLlIo7cMDih0ezvGfjKYuEmHksv5/1vYTk7zWIhG6cvUwvRTF7tcxUPZ0YY3u0JmtaBHyKqfCq0ySGN8WFMUn/y8i3sfKfX1urVY56CgLf6rm0VwG411wIDA7k2/gynFwiwk4PQCFPGoN6lLb8EBvZVY6NU1L0nOm0DSc71NnKidiYmdb+W5PWkQwF8L+BN8JY4O/HC6c/eyU/pSy/o1qmv2cbPSNSDosSeO9k8lk5iTpB81+MbEyCGtWrKszXZSA7b6ex8YdP5Z/OpFeewWpS57V17uUfxbJKQXHDBYTTkVzJ9svRHz1vn9gWX82D5WEycaeaPh6B+ZnzOhJr/c/8o+icblUhV5gALh8j7pYn2oDD9k/6xbVzRlHwDbIixLEKDbAx6ymb4dIucKdjdNretHbv6S61UZn3hnV7IA1YXe0moxKrs1iWkNvcXzaCZRi+zlL8cA8juj+6FSE4WeNLZtpZUsrHiMAf/Cx2dXdZWI6UbkEXoVqRu1dkk3RRrhyx0a0wc7eHhqSc5j8FaQ6s8xAmNIy4h5lmF4tVe75E+KSTZ7Zm4fpBTosanRYFFfx8n6+j8u/RFyoCIY4Mh9EfJs/KYwjadSQ9Qwwr0PkHGC4425Tk6I3n2QZ8KHxWWIbMLsdEAhVxMEAuN5GrfS92h0sARg9H9/e0XykCN3bVpKVqvsB0exNErHyYq1S5fFdYSMhSlajPlBa2I9p9KCy9+UiH3+bClY4EduyLV+cTCbXWRKQSqtUdZ6AYu9EDxVh8gaOFSOekVZ/Md+lIy+cDHx7JBvP9rW4XgUzgnJ+jzwhoXVRS4HfeCwCdv0T+PgLGtbb5xO8X7QoagCBG8vRNrdana6YDMa7L8u9nU7WnrbbfPeYfGN17LOLvJX3/qWG86zwRCMRd88QyNMcHe1abScGDBQRC+jV5ASZ1OWfIrX+Z2oPK53hsMlz0uf57F1WdiE8HR2nQ67XbHBsh23RzhnMCkKru6AuDqHq0/\\\"";

- (NSString *)description
{
  return [@{
            @"segmentWriteKey": self.segmentWriteKey,
  } description];
}

- (id)debugQuickLookObject
{
  return [self description];
}

@end
