//
// Generated by CocoaPods-Keys
// on 07/10/2022
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSDictionary.h>
#import "QuadPaySDKKeys.h"

@interface QuadPaySDKKeys ()

@property (nonatomic, copy) NSString *segmentWriteKey;


@end

@implementation QuadPaySDKKeys

- (instancetype)init
{
    if (!(self = [super init])) { return nil; }

    
    
      char segmentWriteKeyCString[33] = { [QuadPaySDKKeysData characterAtIndex:556], [QuadPaySDKKeysData characterAtIndex:340], [QuadPaySDKKeysData characterAtIndex:807], [QuadPaySDKKeysData characterAtIndex:616], [QuadPaySDKKeysData characterAtIndex:881], [QuadPaySDKKeysData characterAtIndex:479], [QuadPaySDKKeysData characterAtIndex:481], [QuadPaySDKKeysData characterAtIndex:812], [QuadPaySDKKeysData characterAtIndex:115], [QuadPaySDKKeysData characterAtIndex:912], [QuadPaySDKKeysData characterAtIndex:68], [QuadPaySDKKeysData characterAtIndex:575], [QuadPaySDKKeysData characterAtIndex:51], [QuadPaySDKKeysData characterAtIndex:58], [QuadPaySDKKeysData characterAtIndex:830], [QuadPaySDKKeysData characterAtIndex:970], [QuadPaySDKKeysData characterAtIndex:389], [QuadPaySDKKeysData characterAtIndex:580], [QuadPaySDKKeysData characterAtIndex:638], [QuadPaySDKKeysData characterAtIndex:814], [QuadPaySDKKeysData characterAtIndex:490], [QuadPaySDKKeysData characterAtIndex:635], [QuadPaySDKKeysData characterAtIndex:752], [QuadPaySDKKeysData characterAtIndex:867], [QuadPaySDKKeysData characterAtIndex:491], [QuadPaySDKKeysData characterAtIndex:774], [QuadPaySDKKeysData characterAtIndex:305], [QuadPaySDKKeysData characterAtIndex:469], [QuadPaySDKKeysData characterAtIndex:436], [QuadPaySDKKeysData characterAtIndex:173], [QuadPaySDKKeysData characterAtIndex:168], [QuadPaySDKKeysData characterAtIndex:904], '\0' };
    
    _segmentWriteKey = 
        
          [NSString stringWithCString:segmentWriteKeyCString encoding:NSUTF8StringEncoding];
        
      
    

    return self;
}

static NSString *QuadPaySDKKeysData = @"jSYoURaY7yJmaPjQQoMIDGd99JriDb0SrraFeZg+xl+aQ6WkmP3RDa0PMsAO+nW2eTpMoIwma4dcjEDCB3+2mxSBocssGim7rdMInzqzouvGtFRKG3WF//mFl8xcPsmSoZNuRpxGnwGW5ynov/K6QAZGMTS5Z+qp/wr55qt5SgwbS7wAplZTzliIxjwAP+h+mAbf7UXK3/GtP8i5CXX0kiyi8EJo9ln82VWzy+i6H0IIGoddheF1PZCuuRfhgpTAqNEYXr6QaQpMv4S9+TMiOiTL0kWj1IzDn5HXxW4X74ZyOcXrYF1pMJcClf0HzJpIDIX1VBt76zjo2y4vgtJQj227FvfeFs89LK71Ugaj/Iw6lMtF0FMCaESVTnU4FLnnG0mlgB6YLb1YfMgvO9nUGeuiPQF8mPvxNNRKcRuUDSxeV2bgjkwp4d8hAmuA3mPHWLlQHAaqcPKxKjG5HG9aOSLYdSBvL5le0HRj5WILTbr7ZzGCQGYqSsPdgMniAal3MnuvglRAgqUhzQxEczDE3QTO2w1WhuV+6RwTe9pDCDwkcBEWkAw1iIFTn/Azbr+W0Dgz9UwkvaY/5PBspKaLDn7G/cqa7YhFgresbLxOpuMXt09SW1Hnl8DNjDBsCd5pA0lbWk4Ex/zb5E6ydUODA5yb1GxDgn8nh1bB9nFVhsbF7Mr7mwG1+lZJBJ8LfK4MMfEYkYm/64stAcMVBKno8heeSEh6WwO6ehrQ68KtFOeRfn1nCkDPJbk/3wlHgtaFYzfv0ofspSDw7uISJGCVqc2vw3FmGCkljBxEokraAtGJI1zwZz9bppaqv2D+vFLEqLB8sNamc14+INJl1ZEgqOcL9EhcRoLBtvLXofWhX1ZmN6h/oZhO5z2ZnFfRG8gLBV0QIIHGEDXb61IDnITw8GrnD4d08whkrwqEqR2rtkD3iuQPmmVT+JIoPCsmtrfyEOUx8Cg+t+IwebhmedunfA==\\\"";

- (NSString *)description
{
  return [@{
            @"segmentWriteKey": self.segmentWriteKey,
  } description];
}

- (id)debugQuickLookObject
{
  return [self description];
}

@end
