//
// Generated by CocoaPods-Keys
// on 29/11/2022
// For more information see https://github.com/orta/cocoapods-keys
//

#import <Foundation/NSString.h>

NS_ASSUME_NONNULL_BEGIN

@interface QuadPaySDKKeys : NSObject

@property (readonly) NSString *segmentWriteKey;
@property (readonly) NSString *merchantConfigApiUrl;

@end

NS_ASSUME_NONNULL_END
